#!/usr/bin/env python

import sys

from wheelchair_plugin.my_module import MyPlugin
from rqt_gui.main import Main

plugin = 'wheelchair_plugin'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
